### ISSUE TITLE
Hide archived repositories

### ISSUE THREAD

**Issue by marns93** [and-action/and-action#111]
@pchorus Is it possible to hide archived repositories in the configuration? Otherwise, it would be helpful to see that the repository is archived.
I would prefer to not show archived repositories. :)

Thank you!

**Comment by pchorus** [comment]
@marns93 I would suggest to label archived repositories as such. So you can still select them to show up in actions view and commits view, but you actually see that the repository is archived. I don't see why those repositories should not be shown at all, but I agree that it is interesting to see that they are archived.

I will come up with a proposal at some point.
